export enum EConnectionStatus{
    NetworkError = 'No tienes una conexión estable a internet, intenta nuevamente',
}

export enum EOrderProductQty{
    Min = 1,
}

export enum ECoin{
    PEN = {
        name: 'soles',
        symbol: 'S/',
        code: 'PEN',
    },
    USD = {
        name: 'dólares',
        symbol: '$',
        code: 'USD',
    }
}

export enum ETax{
    Peru = .18,
}

export enum EShippingDestination{
    Inplace_Surco = 'en el local de Te lo llevo en Surco (Av. Higuereta 623, Santiago de Surco - Lima)',
    Town = 'dentro de Lima',
    Province = 'a provincia'
}

export enum ECountry {
    Afganistán = 'Afganistán',
    Albania = 'Albania',
    Alemania = 'Alemania',
    Andorra = 'Andorra',
    Angola = 'Angola',
    Antigua_y_barbuda = 'Antigua y barbuda',
    Arabia_saudí = 'Arabia saudí',
    Argelia = 'Argelia',
    Argentina = 'Argentina',
    Armenia = 'Armenia',
    Aruba = 'Aruba',
    Australia = 'Australia',
    Austria = 'Austria',
    Azerbaiyán = 'Azerbaiyán',
    Bahamas = 'Bahamas',
    Bahréin = 'Bahréin',
    Bangladesh = 'Bangladesh',
    Barbados = 'Barbados',
    Belarrús = 'Belarrús',
    Belice = 'Belice',
    Benín = 'Benín',
    Bolivia = 'Bolivia',
    Bosnia_herzegovina = 'Bosnia-herzegovina',
    Botsuana = 'Botsuana',
    Brasil = 'Brasil',
    Brunéi = 'Brunéi',
    Bulgaria = 'Bulgaria',
    Burkina_faso = 'Burkina faso',
    Burundi = 'Burundi',
    Bután = 'Bután',
    Bélgica = 'Bélgica',
    Cabo_verde = 'Cabo verde',
    Camboya = 'Camboya',
    Camerún = 'Camerún',
    Canadá = 'Canadá',
    Catar = 'Catar',
    Chad = 'Chad',
    Chile = 'Chile',
    China = 'China',
    Chipre = 'Chipre',
    Colombia = 'Colombia',
    Comoras = 'Comoras',
    Congo = 'Congo',
    Costa_rica = 'Costa rica',
    Croacia = 'Croacia',
    Cuba = 'Cuba',
    Curazao = 'Curazao',
    Côte_d_ivoire = `Côte d'ivoire`,
    Dinamarca = 'Dinamarca',
    Dominica = 'Dominica',
    Ecuador = 'Ecuador',
    Egipto = 'Egipto',
    El_salvador = 'El salvador',
    Emiratos_árabes_unidos = 'Emiratos árabes unidos',
    Eritrea = 'Eritrea',
    Eslovaquia = 'Eslovaquia',
    Eslovenia = 'Eslovenia',
    España = 'España',
    Estado_de_la_ciudad_del_vaticano = 'Estado de la ciudad del vaticano',
    Estado_de_palestina = 'Estado de palestina',
    Estados_unidos = 'Estados unidos',
    Estonia = 'Estonia',
    Eswatini = 'Eswatini',
    Etiopía = 'Etiopía',
    Filipinas = 'Filipinas',
    Finlandia = 'Finlandia',
    Fiyi = 'Fiyi',
    Francia = 'Francia',
    Gabón = 'Gabón',
    Gambia = 'Gambia',
    Georgia = 'Georgia',
    Ghana = 'Ghana',
    Granada = 'Granada',
    Grecia = 'Grecia',
    Guatemala = 'Guatemala',
    Guinea = 'Guinea',
    Guinea_bissau = 'Guinea bissau',
    Guinea_ecuatorial = 'Guinea ecuatorial',
    Guyana = 'Guyana',
    Haití = 'Haití',
    Honduras = 'Honduras',
    Hungría = 'Hungría',
    India = 'India',
    Indonesia = 'Indonesia',
    Irak = 'Irak',
    Irlanda = 'Irlanda',
    Irán = 'Irán',
    Islandia = 'Islandia',
    Israel = 'Israel',
    Italia = 'Italia',
    Jamaica = 'Jamaica',
    Japón = 'Japón',
    Jordania = 'Jordania',
    Kazajstán = 'Kazajstán',
    Kenia = 'Kenia',
    Kirguistán = 'Kirguistán',
    Kiribati = 'Kiribati',
    Kuwait = 'Kuwait',
    Laos = 'Laos',
    Lesoto = 'Lesoto',
    Letonia = 'Letonia',
    Liberia = 'Liberia',
    Libia = 'Libia',
    Liechtenstein = 'Liechtenstein',
    Lituania = 'Lituania',
    Luxemburgo = 'Luxemburgo',
    Líbano = 'Líbano',
    Macedonia_del_norte = 'Macedonia del norte',
    Madagascar = 'Madagascar',
    Malasia = 'Malasia',
    Malaui = 'Malaui',
    Maldivas = 'Maldivas',
    Malta = 'Malta',
    Malí = 'Malí',
    Marruecos = 'Marruecos',
    Marshall_islas = 'Marshall (islas)',
    Mauricio = 'Mauricio',
    Mauritania = 'Mauritania',
    Moldova = 'Moldova',
    Mongolia = 'Mongolia',
    Montenegro = 'Montenegro',
    Mozambique = 'Mozambique',
    Myanmar = 'Myanmar',
    México = 'México',
    Mónaco = 'Mónaco',
    Namibia = 'Namibia',
    Nauru = 'Nauru',
    Nepal = 'Nepal',
    Nicaragua = 'Nicaragua',
    Nigeria = 'Nigeria',
    Noruega = 'Noruega',
    Nueva_zelanda = 'Nueva zelanda',
    Níger = 'Níger',
    Omán = 'Omán',
    Pakistán = 'Pakistán',
    Panamá = 'Panamá',
    Papúa_nueva_guinea = 'Papúa nueva guinea',
    Paraguay = 'Paraguay',
    Países_bajos = 'Países bajos',
    Perú = 'Perú',
    Polonia = 'Polonia',
    Portugal = 'Portugal',
    Reino_unido = 'Reino unido',
    Rep_centroafricana = 'Rep. centroafricana',
    Rep_checa = 'Rep. checa',
    Rep_dominicana = 'Rep. dominicana',
    Ruanda = 'Ruanda',
    Rumania = 'Rumania',
    Rusia = 'Rusia',
    Salomón_islas = 'Salomón (islas)',
    Samoa = 'Samoa',
    San_cristóbal_y_nieves = 'San cristóbal y nieves',
    San_marino = 'San marino',
    San_martín = 'San martín',
    San_vicente_y_las_granadinas = 'San vicente y las granadinas',
    Santa_lucía = 'Santa lucía',
    Santo_tomé_y_príncipe = 'Santo tomé y príncipe',
    Senegal = 'Senegal',
    Serbia = 'Serbia',
    Seychelles = 'Seychelles',
    Sierra_leone = 'Sierra leone',
    Singapur = 'Singapur',
    Siria = 'Siria',
    Somalia = 'Somalia',
    Sri_lanka = 'Sri lanka',
    Sudáfrica = 'Sudáfrica',
    Sudán = 'Sudán',
    Sudán_del_sur = 'Sudán del sur',
    Suecia = 'Suecia',
    Suiza = 'Suiza',
    Surinam = 'Surinam',
    Tailandia = 'Tailandia',
    Tanzania = 'Tanzania',
    Tayikistán = 'Tayikistán',
    Timor_leste = 'Timor-leste',
    Togo = 'Togo',
    Tonga = 'Tonga',
    Trinidad_y_tobago = 'Trinidad y tobago',
    Turkmenistán = 'Turkmenistán',
    Túnez = 'Túnez',
    Türkiye = 'Türkiye',
    Ucrania = 'Ucrania',
    Uganda = 'Uganda',
    Uruguay = 'Uruguay',
    Uzbekistán = 'Uzbekistán',
    Vanuatu = 'Vanuatu',
    Venezuela = 'Venezuela',
    Vietnam = 'Vietnam',
    Yemen = 'Yemen',
    Yibuti = 'Yibuti',
    Zambia = 'Zambia',
    Zimbabue = 'Zimbabue',
}

export enum EFormat{
    Raw = 'raw',
    Related = 'related',
    Pretty = 'pretty'
}

export enum EMenu{
    Orders = {
        page: 'orders',
        icon: 'packages.svg',
        name: 'pedido',
    },
    Flights = {
        page: 'flights',
        icon: 'airplane.svg',
        name: 'vuelo',
    }
}